CREATE DATABASE inventory_system;
USE inventory_system;
CREATE TABLE PRODUCTS(
ID INT PRIMARY KEY AUTO_INCREMENT,
SKU VARCHAR(255) UNIQUE NOT NULL,
QUANTITY INT,
NAME VARCHAR(255) NOT NULL,
PRICE DECIMAL (10,2) NOT NULL)

SELECT * FROM PRODUCTS;
