CREATE DATABASE inventory_system;
USE inventory_system;
CREATE TABLE PRODUCTS(
ID INT PRIMARY KEY AUTO_INCREMENT,
SKU VARCHAR(255) UNIQUE NOT NULL,
QUANTITY INT,
NAME VARCHAR(255) NOT NULL,
PRICE DECIMAL (10,2) NOT NULL
)

SELECT * FROM PRODUCTS;
CREATE TABLE SUPPLIERS(
SUPPLIER_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME varchar(255) NOT NULL,
EMAIL varchar(255) NOT NULL
)
SELECT * FROM SUPPLIERS;

CREATE TABLE PRODUCT_SUPPLIERS(
PRODUCT_ID INT,
SUPPLIER_ID INT,
WHOLESALE_PRICE DECIMAL(10, 2),
LEAD_TIME_DAYS INT,
PRIMARY KEY (PRODUCT_ID, SUPPLIER_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID));

CREATE TABLE orders (
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_ID INT,
    DATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    QUANTITY_SOLD INT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID)
);

CREATE TABLE RESTOCK(
RESTOCK_ID INT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_ID INT,
SUPPLIER_ID INT,
DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
QUANTITY_ADDED INT NOT NULL,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
);

SELECT * FROM PRODUCT_SUPPLIERS;

